<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="MAIN" Id="{dc0d4c5e-0206-4989-a94b-d2663c998078}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[Axis_01_Function_Blocks ();
Axis_01_Logic ();
Axis_02_Function_Blocks ();
Axis_02_Logic ();
Axis_03_Function_Blocks ();
Axis_03_Logic ();
Axis_04_Function_Blocks ();
Axis_04_Logic ();
Axis_05_Function_Blocks ();
Axis_05_Logic ();
Axis_06_Function_Blocks ();
Axis_06_Logic ();
Axis_07_Function_Blocks ();
Axis_07_Logic ();
Axis_08_Function_Blocks ();
Axis_08_Logic ();
Axis_09_Function_Blocks ();
Axis_09_Logic ();
Axis_10_Function_Blocks ();
Axis_10_Logic ();
Axis_11_Function_Blocks ();
Axis_11_Logic ();
Axis_12_Function_Blocks ();
Axis_12_Logic ();
Axis_13_Function_Blocks ();
Axis_13_Logic ();
Axis_14_Function_Blocks ();
Axis_14_Logic ();
Axis_15_Function_Blocks ();
Axis_15_Logic ();
Axis_16_Function_Blocks ();
Axis_16_Logic ();
Group_01_Function_Blocks ();
Group_01_Logic ();
Group_02_Function_Blocks ();
Group_02_Logic ();
Group_03_Function_Blocks ();
Group_03_Logic ();
Group_04_Function_Blocks ();
Group_04_Logic ();
Group_05_Function_Blocks ();
Group_05_Logic ();
Group_06_Function_Blocks ();
Group_06_Logic ();
Group_07_Function_Blocks ();
Group_07_Logic ();
Group_08_Function_Blocks ();
Group_08_Logic ();
Indicators ();
GVL.UI.WatchdogAction();


]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="91" Count="51" />
      <LineId Id="22" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>