<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{dc0d4c5e-0206-4989-a94b-d2663c998078}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[Axis_01_Function_Blocks ();
Axis_01_Logic ();
Axis_02_Function_Blocks ();
Axis_02_Logic ();
Axis_03_Function_Blocks ();
Axis_03_Logic ();
Axis_04_Function_Blocks ();
Axis_04_Logic ();
Axis_05_Function_Blocks ();
Axis_05_Logic ();
Axis_06_Function_Blocks ();
Axis_06_Logic ();
Axis_07_Function_Blocks ();
Axis_07_Logic ();
Axis_08_Function_Blocks ();
Axis_08_Logic ();
Axis_09_Function_Blocks ();
Axis_09_Logic ();
Axis_10_Function_Blocks ();
Axis_10_Logic ();
Axis_11_Function_Blocks ();
Axis_11_Logic ();
Axis_12_Function_Blocks ();
Axis_12_Logic ();
Axis_13_Function_Blocks ();
Axis_13_Logic ();
Axis_14_Function_Blocks ();
Axis_14_Logic ();
Axis_15_Function_Blocks ();
Axis_15_Logic ();
Axis_16_Function_Blocks ();
Axis_16_Logic ();
Group_01_Function_Blocks ();
Group_01_Logic ();
Group_02_Function_Blocks ();
Group_02_Logic ();
Group_03_Function_Blocks ();
Group_03_Logic ();
Group_04_Function_Blocks ();
Group_04_Logic ();
Group_05_Function_Blocks ();
Group_05_Logic ();
Group_06_Function_Blocks ();
Group_06_Logic ();
Group_07_Function_Blocks ();
Group_07_Logic ();
Group_08_Function_Blocks ();
Group_08_Logic ();
Indicators ();


]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="29" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="35" Count="0" />
      <LineId Id="34" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="36" Count="0" />
      <LineId Id="39" Count="0" />
      <LineId Id="42" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="43" Count="0" />
      <LineId Id="46" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="48" Count="0" />
      <LineId Id="47" Count="0" />
      <LineId Id="50" Count="0" />
      <LineId Id="49" Count="0" />
      <LineId Id="52" Count="0" />
      <LineId Id="51" Count="0" />
      <LineId Id="54" Count="0" />
      <LineId Id="53" Count="0" />
      <LineId Id="56" Count="0" />
      <LineId Id="55" Count="0" />
      <LineId Id="58" Count="0" />
      <LineId Id="57" Count="0" />
      <LineId Id="60" Count="0" />
      <LineId Id="59" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="61" Count="0" />
      <LineId Id="64" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="66" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="68" Count="0" />
      <LineId Id="67" Count="0" />
      <LineId Id="70" Count="0" />
      <LineId Id="69" Count="0" />
      <LineId Id="72" Count="0" />
      <LineId Id="71" Count="0" />
      <LineId Id="74" Count="0" />
      <LineId Id="73" Count="0" />
      <LineId Id="76" Count="0" />
      <LineId Id="75" Count="0" />
      <LineId Id="78" Count="0" />
      <LineId Id="77" Count="0" />
      <LineId Id="80" Count="0" />
      <LineId Id="79" Count="0" />
      <LineId Id="18" Count="0" />
      <LineId Id="21" Count="0" />
      <LineId Id="85" Count="0" />
      <LineId Id="22" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>