<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="UIFB" Id="{5f5724ba-b515-4970-a705-6a0dab9d357f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FINAL UIFB
VAR_INPUT
END_VAR
VAR_OUTPUT
	WatchdogExpired: BOOL;
END_VAR
VAR
	WatchdogTON: TON;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="ClearMotionAndJog" Id="{11ef4a45-0560-43fe-bb9d-e74b80ded0b2}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD PUBLIC ClearMotionAndJog : DINT
]]></Declaration>
      <Implementation>
        <ST><![CDATA[GVL.Axis_01_MA_Enable := GVL.Axis_01_MR_Enable := GVL.Axis_01_Jog_Up_Enable := GVL.Axis_01_Jog_Dn_Enable := 
GVL.Axis_02_MA_Enable := GVL.Axis_02_MR_Enable := GVL.Axis_02_Jog_Up_Enable := GVL.Axis_02_Jog_Dn_Enable := 
GVL.Axis_03_MA_Enable := GVL.Axis_03_MR_Enable := GVL.Axis_03_Jog_Up_Enable := GVL.Axis_03_Jog_Dn_Enable := 
GVL.Axis_04_MA_Enable := GVL.Axis_04_MR_Enable := GVL.Axis_04_Jog_Up_Enable := GVL.Axis_04_Jog_Dn_Enable := 
GVL.Axis_05_MA_Enable := GVL.Axis_05_MR_Enable := GVL.Axis_05_Jog_Up_Enable := GVL.Axis_05_Jog_Dn_Enable := 
GVL.Axis_06_MA_Enable := GVL.Axis_06_MR_Enable := GVL.Axis_06_Jog_Up_Enable := GVL.Axis_06_Jog_Dn_Enable := 
GVL.Axis_07_MA_Enable := GVL.Axis_07_MR_Enable := GVL.Axis_07_Jog_Up_Enable := GVL.Axis_07_Jog_Dn_Enable := 
GVL.Axis_08_MA_Enable := GVL.Axis_08_MR_Enable := GVL.Axis_08_Jog_Up_Enable := GVL.Axis_08_Jog_Dn_Enable := 
GVL.Axis_09_MA_Enable := GVL.Axis_09_MR_Enable := GVL.Axis_09_Jog_Up_Enable := GVL.Axis_09_Jog_Dn_Enable := 
GVL.Axis_10_MA_Enable := GVL.Axis_10_MR_Enable := GVL.Axis_10_Jog_Up_Enable := GVL.Axis_10_Jog_Dn_Enable := 
GVL.Axis_11_MA_Enable := GVL.Axis_11_MR_Enable := GVL.Axis_11_Jog_Up_Enable := GVL.Axis_11_Jog_Dn_Enable := 
GVL.Axis_12_MA_Enable := GVL.Axis_12_MR_Enable := GVL.Axis_12_Jog_Up_Enable := GVL.Axis_12_Jog_Dn_Enable := 
GVL.Axis_13_MA_Enable := GVL.Axis_13_MR_Enable := GVL.Axis_13_Jog_Up_Enable := GVL.Axis_13_Jog_Dn_Enable := 
GVL.Axis_14_MA_Enable := GVL.Axis_14_MR_Enable := GVL.Axis_14_Jog_Up_Enable := GVL.Axis_14_Jog_Dn_Enable := 
GVL.Axis_15_MA_Enable := GVL.Axis_15_MR_Enable := GVL.Axis_15_Jog_Up_Enable := GVL.Axis_15_Jog_Dn_Enable := 
GVL.Axis_16_MA_Enable := GVL.Axis_16_MR_Enable := GVL.Axis_16_Jog_Up_Enable := GVL.Axis_16_Jog_Dn_Enable := 
GVL.Axis_17_MA_Enable := GVL.Axis_17_MR_Enable := GVL.Axis_17_Jog_Up_Enable := GVL.Axis_17_Jog_Dn_Enable := 
GVL.Axis_18_MA_Enable := GVL.Axis_18_MR_Enable := GVL.Axis_18_Jog_Up_Enable := GVL.Axis_18_Jog_Dn_Enable := 
GVL.Axis_19_MA_Enable := GVL.Axis_19_MR_Enable := GVL.Axis_19_Jog_Up_Enable := GVL.Axis_19_Jog_Dn_Enable := 
GVL.Axis_20_MA_Enable := GVL.Axis_20_MR_Enable := GVL.Axis_20_Jog_Up_Enable := GVL.Axis_20_Jog_Dn_Enable := 
GVL.Axis_21_MA_Enable := GVL.Axis_21_MR_Enable := GVL.Axis_21_Jog_Up_Enable := GVL.Axis_21_Jog_Dn_Enable := 
GVL.Axis_22_MA_Enable := GVL.Axis_22_MR_Enable := GVL.Axis_22_Jog_Up_Enable := GVL.Axis_22_Jog_Dn_Enable := 
GVL.Axis_23_MA_Enable := GVL.Axis_23_MR_Enable := GVL.Axis_23_Jog_Up_Enable := GVL.Axis_23_Jog_Dn_Enable := 
GVL.Axis_24_MA_Enable := GVL.Axis_24_MR_Enable := GVL.Axis_24_Jog_Up_Enable := GVL.Axis_24_Jog_Dn_Enable := 
0;

ClearMotionAndJog := 0;]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetMotorsGroup" Id="{aff4a827-7071-4903-bfa0-75ca92683f35}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD PUBLIC GetMotorsGroup : DINT
VAR_OUTPUT
	res: ARRAY[0..15] OF INT;
END_VAR
VAR
	ptr: POINTER TO BOOL;
	im, ig:INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ptr := ADR(GVL.Group_01_Axis_01);
MEMSET(destAddr:=ADR(res[0]), fillByte:=0, n:=SIZEOF(res));
FOR ig := 1 TO 8 DO
	FOR im := 0 TO 15 DO
		IF ptr^ THEN
			IF res[im] <> 0 THEN
				ptr^ := 0;
			ELSE
				res[im] := ig;
			END_IF
		END_IF
		ptr := ptr + 1;
	END_FOR
END_FOR

GetMotorsGroup := 0;
RETURN;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="SaveGroupMotors" Id="{14725f97-0d69-4151-8e3a-914062cc559c}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD PUBLIC SaveGroupMotors : DINT
VAR_INPUT
	Group:INT;
	Bitmap:WORD;
END_VAR
VAR
	ptr: POINTER TO BOOL;
	i:INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[ptr := ADR(GVL.Group_01_Axis_01) + Group * 16;

FOR i := 0 TO 15 DO
	ptr^ := (Bitmap AND 1) <> 0;
	ptr := ptr + 1;
	Bitmap := SHR(Bitmap, 1);
END_FOR

SaveGroupMotors := 0;
RETURN;]]></ST>
      </Implementation>
    </Method>
    <Action Name="WatchdogAction" Id="{b48eebc2-f66b-4df4-9e66-ad6a264b9313}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Ld"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"WatchdogExpired"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">9L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"TON"</v>
                          <o n="Instance" t="Operand">
                            <v n="Operand">"WatchdogTON"</v>
                            <v n="Type">"TON"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">18L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems" cet="Operand">
                              <n />
                              <o>
                                <v n="Operand">""</v>
                                <v n="Type">"TIME"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">true</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">6L</v>
                              </o>
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">true</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems" cet="BoxTreeOperand">
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"GVL.Watchdog_OK"</v>
                                <v n="Type">"BOOL"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">true</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">true</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">3L</v>
                              </o>
                              <v n="Id">2L</v>
                            </o>
                            <o>
                              <o n="Operand" t="Operand">
                                <v n="Operand">"T#5s"</v>
                                <v n="Type">"TIME"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">8L</v>
                              </o>
                              <v n="Id">7L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>IN</v>
                              <v>PT</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>TIME</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>Q</v>
                              <v>ET</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>TIME</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">FunctionBlock</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">19L</v>
                        </o>
                        <v n="Id">10L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">1L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"GVL.Watchdog_OK"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">2</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">14L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeOperand">
                          <o n="Operand" t="Operand">
                            <v n="Operand">"GVL.Watchdog_OK"</v>
                            <v n="Type">"BOOL"</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">1</v>
                              <v n="Fixed">true</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">true</v>
                            <v n="IsInstance">false</v>
                            <v n="Id">13L</v>
                          </o>
                          <v n="Id">12L</v>
                        </o>
                        <v n="Id">15L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">11L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <LineIds Name="UIFB">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="UIFB.ClearMotionAndJog">
      <LineId Id="3" Count="25" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="UIFB.GetMotorsGroup">
      <LineId Id="3" Count="16" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="UIFB.SaveGroupMotors">
      <LineId Id="3" Count="8" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>